export BSC_ETHERSCAN_API_KEY=HZF74EH51PK2W1N84BE6W8YYATDP6UEFC2
export ETH_ETHERSCAN_API_KEY=ASW5YSPWJJI8MYHEGP31UVCU2EQJRFFSKY
export POLYGON_ETHERSCAN_API_KEY=GDV24F5FNPUVW9UJCQKY256RKI7ZZVPM6K
export OPTIMISM_ETHERSCAN_API_KEY=ITKZCYG3GB5C16Y8FY1TWBIBKSUJ84W5RB
export FANTOM_ETHERSCAN_API_KEY=8RC7HT9AXEGAGQV9ZKBMYAHJJ8NUMRA792
export ARBITRUM_ETHERSCAN_API_KEY=ITEDDXKERJPRXVVFRCJP897I3V2NQEZNSW
export GNOSIS_ETHERSCAN_API_KEY=BGYHTK4ECGPWYDPGEIFFN6EBVSINFTJZRS
export CELO_ETHERSCAN_API_KEY=V3VTFNGKFPCGURA9BZYIXVA1UX3GVUWW3C

export BSC_RPC_URL=https://bsc-dataseed.bnbchain.org
export ETH_RPC_URL=http://64.71.166.16/eth-chain
export POLYGON_RPC_URL=http://64.71.166.16/polygon-chain
export OPTIMISM_RPC_URL=https://rpc.ankr.com/optimism
export FANTOM_RPC_URL=https://rpc.ankr.com/fantom
export ARBITRUM_RPC_URL=http://64.71.166.16/arbitrum-chain
export GNOSIS_RPC_URL=https://rpc.ankr.com/gnosis
export CELO_RPC_URL=https://rpc.ankr.com/celo
